language: java

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: false
      jdk: openjdk8

# For maven projects, the default installation phase can be skipped
install: true

cache:
  directories:
    - $HOME/.m2/repository

script: ./mvnw clean package install test -DlocalRessources.ressourcePathDirectory=`pwd`/src/main/resources/json/LocalRessources
