spring:
  config:
    activate:
      on-profile: 'default-config'

---

server:
  port: 8090
  servlet:
    context-path: /manon

#logging:
#  config: 'classpath:logback.xml'

spring:
  application:
    name: MediaCentre

  profiles:
    active: @spring.profiles.active@
    group:
      dev: dev

app:
  cors:
    enable: true
    allow-credentials: true
    allowed-origins:

    exposed-headers:
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-headers:
      - content-type
      - authorization
      - x-com-persist
      - X-Auth-Token
      - x-auth-token
      - x-requested-with
      - x-xsrf-token
    allowed-methods:
      - GET
      - PUT
      - POST
      - DELETE

  soffit:
    jwtSignatureKey: ''

viewResCache: false

hostnames:
  trusted:

userInfo:
  key:
    currenEtabId:
      ESCOSIRENCourant
    etabIds:
      ESCOSIREN
    groups:
      isMemberOf
    uid:
      ENTPersonGARIdentifiant
    profils:
      ENTPersonProfils
  mediacentre:
    favorites:
#      a remplacer par l'url de l'api
      mediacentreFavorites

filters:
  categoriesByProfiles:

url:
  ressources:
    mediacentre:


